name: Dave Hulbert
description: "Software design, PHP and technology"
meta_description: "Software design, PHP and technology"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://createopen.com'

# Details for the RSS feed generator
url:            'https://createopen.com'
author:         'Dave Hulbert'
